preprocessing:
  patch_size: 512
  background_fraction: 0.1 # fraction of background patches to save

paths:
  output_dir: "output_imgs/patches3"
  data_dir: "data"

logging:
  logging_dir_name: "mal"
  logger_lvl: "debug"
  console_handler_lvl: "warning"
  file_handler_lvl: "debug"